### PR TITLE
removed mapped_iterator::{size, empty}

### LINKED ISSUE #1427: `mapped_view` returns wrong `size` when filtered
`storage.iterate<Record>(where(...)).size()` returns the size of the full, unfiltered table, instead of the number of records for which the condition holds true. `empty()` is also affected.

Example:
```cpp
#include <iostream>
#include <string>

#include <sqlite_orm/sqlite_orm.h>

struct Person {
    std::string name;
};

int main() {
    using namespace sqlite_orm;

    auto storage = make_storage("my.db",
        make_table("People",
            make_column("name", &Person::name)
        )
    );
    storage.sync_schema();
    storage.insert<Person>(Person("Linus"));
    storage.insert<Person>(Person("Dennis"));
    std::cout << "Linuses: "
        << storage.iterate<Person>(where(c(&Person::name) == "Linus")).size()
        << std::endl;
}
```

Expected output: `Linuses: 1`.
Actual output: `Linuses: 2`.

[Demo on Compiler Explorer](https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,selection:(endColumn:1,endLineNumber:25,positionColumn:1,positionLineNumber:25,selectionStartColumn:1,selectionStartLineNumber:25,startColumn:1,startLineNumber:25),source:'%23include+%3Ciostream%3E%0A%23include+%3Cstring%3E%0A%0A%23include+%3Chttps://raw.githubusercontent.com/fnc12/sqlite_orm/refs/tags/v1.9.1/include/sqlite_orm/sqlite_orm.h%3E%0A%0Astruct+Person+%7B%0A++++std::string+name%3B%0A%7D%3B%0A%0Aint+main()+%7B%0A++++using+namespace+sqlite_orm%3B%0A%0A++++auto+storage+%3D+make_storage(%22my.db%22,%0A++++++++make_table(%22People%22,%0A++++++++++++make_column(%22name%22,+%26Person::name)%0A++++++++)%0A++++)%3B%0A++++storage.sync_schema()%3B%0A++++storage.insert%3CPerson%3E(Person(%22Linus%22))%3B%0A++++storage.insert%3CPerson%3E(Person(%22Dennis%22))%3B%0A++++std::cout+%3C%3C+%22Linuses:+%22%0A++++++++%3C%3C+storage.iterate%3CPerson%3E(where(c(%26Person::name)+%3D%3D+%22Linus%22)).size()%0A++++++++%3C%3C+std::endl%3B%0A%7D%0A'),l:'5',n:'0',o:'C%2B%2B+source+%231',t:'0')),k:52.158799853640694,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((g:!((h:compiler,i:(compiler:clang1810,filters:(b:'0',binary:'1',binaryObject:'1',commentOnly:'0',debugCalls:'1',demangle:'0',directives:'0',execute:'0',intel:'0',libraryCode:'0',trim:'1',verboseDemangling:'0'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,libs:!((name:sqlite,ver:'3400')),options:'-std%3Dc%2B%2B20',overrides:!(),selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1),l:'5',n:'0',o:'+x86-64+clang+18.1.0+(Editor+%231)',t:'0')),k:47.84120014635933,l:'4',m:46.49963154016212,n:'0',o:'',s:0,t:'0'),(g:!((h:output,i:(compilerName:'x86-64+clang+(trunk)',editorid:1,fontScale:14,fontUsePx:'0',j:1,wrap:'1'),l:'5',n:'0',o:'Output+of+x86-64+clang+18.1.0+(Compiler+%231)',t:'0')),header:(),l:'4',m:53.50036845983788,n:'0',o:'',s:0,t:'0')),k:47.84120014635933,l:'3',n:'0',o:'',t:'0')),l:'2',n:'0',o:'',t:'0')),version:4)

### PR DESCRIPTION
**Pull request by fnc12**

### CODE REVIEW

File: tests/static_tests/iterator_t.cpp [hunk 1]
```diff
@@ -52,17 +52,6 @@ concept LegacyInputIterator =
...
 
-template<class Iter, class Value>
-concept can_iterate_mapped = requires(Iter it) {
-    requires LegacyInputIterator<Iter>;
-    // explicit check of the sentinel role, since `std::ranges::borrowed_range` in `can_view_mapped`
-    // would not tell us why exactly the end iterator cannot be a sentinel
-    requires std::sentinel_for<Iter, Iter>;
-    { *it } -> std::same_as<Value&>;
-    // note: should actually be only present for contiguous iterators
-    { it.operator->() } -> std::same_as<Value*>;
```
Comment (trueqbit) [inline tests/static_tests/iterator_t.cpp:63]: Just remove this line from the concept check, not the whole concept!

**Review by trueqbit — CHANGES_REQUESTED** [review]

File: tests/static_tests/iterator_t.cpp (hunk 1 above)
Comment (fnc12) [reply tests/static_tests/iterator_t.cpp:63]: done

**Review by trueqbit — APPROVED** [review]
