### PR TITLE
Code quality

### LINKED ISSUE #1409: Compilation errors with clang on windows: `error: constexpr variable 'value' must be initialized by a constant expression`
```c++
D:\LLVM\bin\clang-cl.exe   -TP  -imsvcD:\Clion\vcpkg\installed\x64-windows\include /DWIN32 /D_WINDOWS /EHsc /Ob0 /Od /RTC1 -std:c++latest -MDd -Zi /clang:-Wall -Wextra -Wpedantic -Wconversion /showIncludes /FoCMakeFiles\rundll.dir\main.cpp.obj /FdCMakeFiles\rundll.dir\ -c -- D:\Clion\Project\rundll\main.cpp
In file included from D:\Clion\Project\rundll\main.cpp:1:
In file included from E:\VS\ToolChain\VC\Tools\MSVC\14.43.34808\include\fstream:10:
In file included from E:\VS\ToolChain\VC\Tools\MSVC\14.43.34808\include\__msvc_filebuf.hpp:12:
In file included from E:\VS\ToolChain\VC\Tools\MSVC\14.43.34808\include\streambuf:10:
In file included from E:\VS\ToolChain\VC\Tools\MSVC\14.43.34808\include\xiosbase:11:
In file included from E:\VS\ToolChain\VC\Tools\MSVC\14.43.34808\include\system_error:10:
In file included from E:\VS\ToolChain\VC\Tools\MSVC\14.43.34808\include\__msvc_system_error_abi.hpp:10:
In file included from E:\VS\ToolChain\VC\Tools\MSVC\14.43.34808\include\cstddef:12:
E:\VS\ToolChain\VC\Tools\MSVC\14.43.34808\include\xtr1common(27,26): error: constexpr variable 'value' must be initialized by a constant expression
   27 |     static constexpr _Ty value = _Val;
      |                          ^       ~~~~
E:\VS\ToolChain\VC\Tools\MSVC\14.43.34808\include\xtr1common(33,16): note: in instantiation of static data member 'std::integral_constant<int (*)(sqlite3_stmt *), &sqlite3_finalize>::value' requested here
   33 |         return value;
      |                ^
E:\VS\ToolChain\VC\Tools\MSVC\14.43.34808\include\memory(3409,13): note: in instantiation of member function 'std::integral_constant<int (*)(sqlite3_stmt *), &sqlite3_finalize>::operator int (*)(sqlite3_stmt *)' requested here
 3409 |             _Mypair._Get_first()(_Mypair._Myval2);
      |             ^
D:\Clion\vcpkg\installed\x64-windows\include\sqlite_orm/sqlite_orm.h(13652,83): note: in instantiation of member function 'std::unique_ptr<sqlite3_stmt, std::integral_constant<int (*)(sqlite3_stmt *), &sqlite3_finalize>>::~unique_ptr' requested here
 13652 |             mapped_iterator(const db_objects_type& dbObjects, statement_finalizer stmt) :
       |                                                                                   ^
In file included from D:\Clion\Project\rundll\main.cpp:1:
In file included from E:\VS\ToolChain\VC\Tools\MSVC\14.43.34808\include\fstream:10:
In file included from E:\VS\ToolChain\VC\Tools\MSVC\14.43.34808\include\__msvc_filebuf.hpp:12:
In file included from E:\VS\ToolChain\VC\Tools\MSVC\14.43.34808\include\streambuf:10:
In file included from E:\VS\ToolChain\VC\Tools\MSVC\14.43.34808\include\xiosbase:11:
In file included from E:\VS\ToolChain\VC\Tools\MSVC\14.43.34808\include\system_error:10:
In file included from E:\VS\ToolChain\VC\Tools\MSVC\14.43.34808\include\__msvc_system_error_abi.hpp:10:
In file included from E:\VS\ToolChain\VC\Tools\MSVC\14.43.34808\include\cstddef:12:
E:\VS\ToolChain\VC\Tools\MSVC\14.43.34808\include\xtr1common(27,26): error: constexpr variable 'value' must be initialized by a constant expression
   27 |     static constexpr _Ty value = _Val;
      |                          ^       ~~~~
E:\VS\ToolChain\VC\Tools\MSVC\14.43.34808\include\xtr1common(33,16): note: in instantiation of static data member 'std::integral_constant<void (*)(void *), &sqlite3_free>::value' requested here
   33 |         return value;
      |                ^
E:\VS\ToolChain\VC\Tools\MSVC\14.43.34808\include\memory(3409,13): note: in instantiation of member function 'std::integral_constant<void (*)(void *), &sqlite3_free>::operator void (*)(void *)' requested here
 3409 |             _Mypair._Get_first()(_Mypair._Myval2);
      |             ^
D:\Clion\vcpkg\installed\x64-windows\include\sqlite_orm/sqlite_orm.h(14189,30): note: in instantiation of member function 'std::unique_ptr<char, std::integral_constant<void (*)(void *), &sqlite3_free>>::~unique_ptr' requested here
 14189 |                 if (char_ptr sql{sqlite3_expanded_sql(this->stmt)}) {
       |                              ^
```

I found the following, and it seems that clang does not yet support `constexpr` constraints for a `dllimport` function.

https://github.com/llvm/llvm-project/issues/125952
https://github.com/llvm/llvm-project/issues/50900

Possible solutions:
```c++
#ifdef __clang__
        struct sqlite3_finalizer {
            int operator()(sqlite3_stmt *pStmt) {
                return sqlite3_finalize(pStmt);
            }
        };
        using statement_finalizer = std::unique_ptr<sqlite3_stmt, sqlite3_finalizer>;
#else
    using statement_finalizer =
        std::unique_ptr<sqlite3_stmt, std::integral_constant<decltype(&sqlite3_finalize), sqlite3_finalize>>;
#endif
```
```c++
#ifdef __clang__
                struct sqlite3_freer {
                    void operator()(void* ptr) {
                        sqlite3_free(ptr);
                    }
                };
                using char_ptr = std::unique_ptr<char, sqlite3_freer>;
#else
                using char_ptr = std::unique_ptr<char, std::integral_constant<decltype(&sqlite3_free), sqlite3_free>>;
#endif
```

### PR DESCRIPTION
**Pull request by trueqbit**
New Visual C++ 18 2026 as well as Clang 21 are out. In an attempt to compile sqlite_orm with these new toolchains I corrected and improved things along the way.

Fixes:
* Corrected deprecated spacing in user-defined literal operators, e.g. `operator"" _cte()` -> `operator""_cte()`.

Generic improvements:
* Updated to clang-format 20.
* Used the single-argument version of `static_assert`, which was not possible with C++14 before.
* Removed a few unused type aliases in unit tests.
* Addressed a few warnings about unused variables.

Clang related:
* Temporarily disable spurious Clang warnings instead of suppressing them in code, which makes code cleaner and less likely to forget to suppress them on spot.
* Clang understands C++26 features even in C++17 mode, but it doesn't mean it understands other language features, so we need to be specific using them.
* Needed to disable compiling the R*Tree module with Clang because Clang chokes on using constexpr variables in lambdas. This is an unfixed issue reported several times to the Clang maintainers.

Clang MSVC:
* Made sqlite_orm compile with Clang MSVC. Specifically it still cannot use functions exported from DLLs as compile-time parameters, so we provide workarounds for it.

### CODE REVIEW

File: dev/storage.h [hunk 1]
```diff
@@ -1656,7 +1656,7 @@ namespace sqlite_orm {
                     this->executor.will_run_query(sql);
                 }
 
-                switch (int rc = sqlite3_step(stmt)) {
+                switch (/*int rc =*/sqlite3_step(stmt)) {
```
Comment (fnc12) [inline dev/storage.h]: this thing makes it harder to debug and watch returned value from `sqlite3_step` sometimes

**Review by fnc12 — APPROVED** [review]

File: dev/storage.h (hunk 1 above)
Comment (trueqbit) [reply dev/storage.h]: You are right, I think we can just use `[[maybe_unused]]` in such cases.

**Review by fnc12 — APPROVED** [review]

**Review by fnc12 — APPROVED** [review]
