### PR TITLE
Fix for race condition in relation to error handling for query errors

### LINKED ISSUE #1416: Race condition between the execution of a statement and the retrieval of the last error from SQLite
> [...] sqlite_orm is doing some thread-unsafe calls that it doesn't have to do, and could definitely use some improvement in this area.  For example, there is *lots* of code that looks like this:
> 
> ```C++
> if(sqlite3_step(stmt) == SQLITE_DONE) {
>     //  done..
> } else {
>     throw std::system_error(std::error_code(sqlite3_errcode(db), get_sqlite_error_category()),
>                             sqlite3_errmsg(db));
> }
> ```
> 
> which isn't thread safe because there's a race condition between the `sqlite3_step(stmt)` and the `sqlite3_errcode(db)/sqlite3_errmsg(db)` calls, which means the code and message in the exception aren't reliable when used multithreaded.
> 
> 
> If I was writing it using raw libsqlite3, then I would write it to be thread-safe by writing it as:
> ```C++
> auto rc = sqlite3_step(stmt);
> if (rc == SQLITE_DONE) {
>     // done..
> } else {
>     throw std::system_error(std::error_code(rc, get_sqlite_error_category()), sqlite3_errstr(rc));
> }
> ```
> 
> but I *can't* currently get that thread safety with sqlite_orm.

 _Originally posted by @jagerman in [#707](https://github.com/fnc12/sqlite_orm/issues/707#issuecomment-859649406)_

### PR DESCRIPTION
**Pull request by trueqbit**
This PR addresses a [comment by @jagerman](https://github.com/fnc12/sqlite_orm/issues/707#issuecomment-859649406).

The problem solved is the race condition between executing a statement and retrieving the last error from SQLite.
There are two ways to fix this: Either handle errors solely based on the return code of an API call. Or serialize access to the DB handle.

This PR implements handling errors based on the return code.

When handling errors solely based on the return code, SQLite obviously cannot provide as much information as to why (or where) a statement failed. I consider this as a flaw in SQLite as it would be easily solvable with storing the last error per thread in the SQLite3 library.

Important things to know:
* The library can handle empty ranges of insert/replace statements and unregistered function errors up-front. SQLite would only return a generic `SQLITE_ERROR` error value.
* Checking missing application-defined collation sequences wasn't pursued because SQLite will at least return a dedicated `SQLITE_ERROR_MISSING_COLLSEQ` extended error value. It would be easily implementable.
* Detailed information of constraint errors [`SQLITE_CONSTRAINT_*`], e.g. about the specific column violating a constraint (e.g. primary key, foreign key, not null) is lost; only the type of constraint violation is known.

Additional improvements:
* Enabled SQLite extended error codes
* Maximum efficient result row stepping loop. Returning instead of looping on a condition saves a couple of instructions.

### CODE REVIEW

File: dev/storage.h [hunk 1]
```diff
@@ -1202,6 +1238,10 @@ namespace sqlite_orm {
 
             template<typename S>
             prepared_statement_t<S> prepare_impl(S statement) {
+#if defined(SQLITE_ORM_IF_CONSTEXPR_SUPPORTED) && __cpp_lib_is_invocable >= 201703L
+                iterate_ast(statement, udf_presence_checker{this->scalarFunctions, this->aggregateFunctions});
```
Comment (fnc12) [inline dev/storage.h]: we don't need to iterate AST one more time if `this->scalarFunctions.empty() && this->aggregateFunctions.empty()`. We can add `if` for that to skip increasing `prepare_impl` work time for people who never binds application defined funcs

File: dev/ast_iterator.h [hunk 2]
```diff
@@ -52,17 +53,28 @@ namespace sqlite_orm {
...
+         *  The callable can opt in to be invoked for a node expression.
          */
         template<class T, class L>
         void iterate_ast(const T& t, L&& lambda) {
             ast_iterator<T> iterator;
+
+#if defined(SQLITE_ORM_IF_CONSTEXPR_SUPPORTED) && __cpp_lib_is_invocable >= 201703L
+            // possibly invoke lambda with node itself
+            if constexpr (std::is_invocable<L, polyfill::bool_constant<true>, const T&>::value) {
+                lambda(polyfill::bool_constant<true>{}, t);
```
Comment (fnc12) [inline dev/ast_iterator.h]: where do we use it?

Comment (trueqbit) [reply dev/ast_iterator.h]: The `udf_presence_checker` uses it.

File: dev/storage.h (hunk 1 above)
Comment (trueqbit) [reply dev/storage.h]: Unfortunately skipping the AST iteration is impossible. We need to examine the AST for function calls, and throw an error if the function wasn't registered earlier.

File: dev/ast_iterator.h (hunk 2 above)
Comment (trueqbit) [reply dev/ast_iterator.h]: ... and now also the table name collector.

File: dev/storage.h (hunk 1 above)
Comment (fnc12) [reply dev/storage.h]: wait but if we have `this->scalarFunctions.empty() && this->aggregateFunctions.empty()` it means we find nothing

File: tests/ast_iterator_tests.cpp [hunk 3]
```diff
@@ -10,16 +10,41 @@ using internal::column_alias;
 using internal::column_pointer;
 using internal::iterate_ast;
 
+#if __cpp_generic_lambdas >= 201707L
+template<class... L>
+struct overload : L... {
```
Comment (fnc12) [inline tests/ast_iterator_tests.cpp]: this is the best part of C++ =)

**Review by fnc12 — APPROVED** [review]

File: dev/storage.h (hunk 1 above)
Comment (trueqbit) [reply dev/storage.h]: You can write a statement that uses a function that you didn't register (create) before... So if both containers are empty it is an error - in order to find out whether a function call is in a statement we need to examine the statement.

Comment (fnc12) [reply dev/storage.h]: ah I see. Ok
